# products API

###
# baseURL
@baseURL = http://localhost:5000/wishlist

###
# Find All wishlist
GET {{baseURL}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjMyNDk3NTY2LCJleHAiOjE2MzI1MDExNjZ9.HavxVg-nbPwN2ZQtf-Vy7DrrnaZfSYGQDRYUR_j-GQI

###
# Find wishlist By Id
GET {{baseURL}}/1

###
# Add wishlist By Id
POST {{baseURL}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjMyNTYwMDA2LCJleHAiOjE2MzI1NjM2MDZ9.8RZ08sbWP8RLgcs2E-Zd3ulrBEBuY0nIrUGhjyUz0cw

{
	"productId": 2
}

###
# Delete wishlist By Id
DELETE {{baseURL}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjMyNDk3NTY2LCJleHAiOjE2MzI1MDExNjZ9.HavxVg-nbPwN2ZQtf-Vy7DrrnaZfSYGQDRYUR_j-GQI
